# PyMOL script for ipSAE visualization
# Generated by ipSAE package

alias color_A_B, color gray80, all; color magenta, chain  A and resi 1-232; color marine, chain  B and resi 1-218

alias color_A_C, color gray80, all; color magenta, chain  A and resi 1-232; color lime, chain  C and resi 1-123

alias color_B_C, color gray80, all; color marine, chain  B and resi 1-218; color lime, chain  C and resi 1-123

